version: '3'
services:
  nodejs-server:
    container_name: node-api
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - prod.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
  angular-ui:
    container_name: angular-ui
    build:
      context: ./myblog
      dockerfile: Dockerfile
    ports:
      - "443:443"
      - "80:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    
