version: '3'
services:  
  angular-ui:
    container_name: angular-ui
    build:
      context: ./myblog
      dockerfile: Dockerfile
    ports:
      - "443:443"
      - "80:80"
  nodejs-server:
    container_name: node-api
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - local.env
    
